# Generated by Django 4.2.7 on 2024-10-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddItems",
            fields=[
                ("Item_id", models.AutoField(primary_key=True, serialize=False)),
                ("ItemName", models.CharField(max_length=255)),
                ("Description", models.TextField()),
                ("Quantity", models.IntegerField()),
            ],
        ),
    ]
